### ISSUE TITLE
Mod incompatible with latest Cold Sweat version

### ISSUE THREAD

**Issue by Kireand** [wiidotmom/mars-popsicle#1]
Minecraft version 1.20.1
Forge Version 47.3.12
Mars Popsicle version 1.0.0
Cold Sweat version 2.3.8
Ad Astra version 1.15.18

Crash during startup:
![image](https://github.com/user-attachments/assets/f405e16c-9472-42f8-bf50-f0a78f3a2d9c)

Crash report:
[crash-2024-11-11_09.26.15-fml.txt](https://github.com/user-attachments/files/17702332/crash-2024-11-11_09.26.15-fml.txt)

**Comment by son0fether** [comment]
I am experiencing this as well.
Minecraft 1.20.1
Mars Popsicle 1.0.0
Cold Sweat 2.3.8
Ad Astra 1.15.18
